name: adadev.io
region: nyc
services:
- name: adadev-frontend
  source_dir: /
  github:
    repo: SLFMR1/ADAdev.io
    branch: main
  run_command: node server.js
  build_command: npm ci && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: VITE_OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${VITE_OPENAI_API_KEY}
    type: SECRET
  - key: GITHUB_TOKEN
    scope: RUN_TIME
    value: ${GITHUB_TOKEN}
    type: SECRET
  - key: NODE_ENV
    value: production
    scope: RUN_TIME
  - key: PORT
    value: "3000"
    scope: RUN_TIME 